---
- name: Managing Supervisord Conf file
  copy: src=supervisord.conf dest=/etc/supervisor/conf.d/chaosmonkey.conf

# Restart chaosmonkey, reading supervisorctl configuration from a specified file.
- supervisorctl: name=chaosmonkey state=restarted config=/etc/supervisor/supervisord.conf
