---
- name: Updates apt cache
  apt: update_cache=true

- name: Update packages
  apt_repository: repo='ppa:webupd8team/java' state=present 

- name: accept oracle license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Installs necessary packages
  apt: pkg={{ item }} state=latest install_recommends=no dpkg_options='force-confold,force-confdef' 
  with_items:
      - oracle-java7-installer
      - git
      - supervisor

- name: Install Chaos Monkey on all systems.
  git: repo=https://github.com/Netflix/SimianArmy.git version=master accept_hostkey=True dest=/opt/SimianArmy

- name: Managing the chaos.properties file.
  copy: src=chaos.properties dest=/opt/SimianArmy/src/main/resources/chaos.properties mode=0644 

- name: Managing the client.properties file.
  copy: src=client.properties dest=/opt/SimianArmy/src/main/resources/client.properties mode=0644 

- name: Managing the simianarmy.properties file.
  copy: src=simianarmy.properties dest=/opt/SimianArmy/src/main/resources/simianarmy.properties mode=0644 

- name: Managing the janitor.properties file.
  copy: src=janitor.properties dest=/opt/SimianArmy/src/main/resources/janitor.properties mode=0644 

- name: Managing the conformity.properties file.
  copy: src=conformity.properties dest=/opt/SimianArmy/src/main/resources/conformity.properties mode=0644 

- name: Managing the volumeTagging.properties file.
  copy: src=volumeTagging.properties dest=/opt/SimianArmy/src/main/resources/volumeTagging.properties mode=0644 

- name: Managing the build.gradle file.
  copy: src=build.gradle dest=/opt/SimianArmy/build.gradle mode=0644 

- name: Running Chaos Gradlew build.
  shell: cd /opt/SimianArmy && ./gradlew build
